/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba;

import br.com.ifba.agendamento.view.TelaDisponibilidadePsicologo;
import br.com.ifba.paciente.view.TelaExibirPacientes;
import br.com.ifba.prontuario.view.ListaProntuarios;
import br.com.ifba.solicitacao.view.TelaExibirSolicitacoes;
import br.com.ifba.usuario.model.Usuario;
import br.com.ifba.usuario.service.IServiceUsuario;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class TelaMenuPsicologo extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenuPsicologo
     */
    @Autowired
    private ListaProntuarios telaListaProntuarios;
    @Autowired
    private TelaExibirPacientes telaExibirPacientes;
    @Autowired
    private TelaDisponibilidadePsicologo telaAgendamento;
    @Autowired
    private TelaExibirSolicitacoes telaExibirSolicitacoes;
    @Autowired
    IServiceUsuario serviceUsuario;
    
    public TelaMenuPsicologo() {
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    public TelaMenuPsicologo(String user) {
        
    }
    
    public void atualizarLabel(String login) {
        lblUserPsicologo.setText(login);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnListProntuarios = new javax.swing.JButton();
        btnDisponAtendimento = new javax.swing.JButton();
        btnListPacientes = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblBemVindo = new javax.swing.JLabel();
        btnListSolicita = new javax.swing.JButton();
        lblUserPsicologo = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("AÇÔES DISPONIVEIS PARA PSICOLOGO");

        btnListProntuarios.setText("Listar Prontuarios");
        btnListProntuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListProntuariosActionPerformed(evt);
            }
        });

        btnDisponAtendimento.setText("Disponibilizar Horario");
        btnDisponAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisponAtendimentoActionPerformed(evt);
            }
        });

        btnListPacientes.setText("Listar Pacientes");
        btnListPacientes.setMaximumSize(new java.awt.Dimension(152, 23));
        btnListPacientes.setMinimumSize(new java.awt.Dimension(152, 23));
        btnListPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListPacientesActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblBemVindo.setText("Bem-vindo,");

        btnListSolicita.setText("Exibir Solicitações");
        btnListSolicita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListSolicitaActionPerformed(evt);
            }
        });

        lblUserPsicologo.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBemVindo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUserPsicologo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(110, 110, 110))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDisponAtendimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListSolicita, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(btnListProntuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDisponAtendimento, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(btnListPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnListProntuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnListSolicita, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBemVindo)
                    .addComponent(lblUserPsicologo))
                .addGap(6, 6, 6)
                .addComponent(btnLogout)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        String login = lblUserPsicologo.getText();
        Usuario usuario = serviceUsuario.findByLogin(login);

        if(usuario != null) {
            usuario.setPerfilUsuario(null); // limpando a associação com o perfilUsuario
        } else 
            System.out.println("Usuário não encontrado para o login: " + login);

        this.dispose(); // fecha o menu atual de psicologo
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnListProntuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListProntuariosActionPerformed
         this.telaListaProntuarios.setVisible(true);
    }//GEN-LAST:event_btnListProntuariosActionPerformed

    private void btnDisponAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisponAtendimentoActionPerformed
        this.telaAgendamento.setVisible(true);
    }//GEN-LAST:event_btnDisponAtendimentoActionPerformed

    private void btnListSolicitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListSolicitaActionPerformed
        this.telaExibirSolicitacoes.atualizarTabela();
        this.telaExibirSolicitacoes.setVisible(true);    }//GEN-LAST:event_btnListSolicitaActionPerformed

    private void btnListPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListPacientesActionPerformed
        this.telaExibirPacientes.setVisible(true);this.telaExibirPacientes.setVisible(true);    }//GEN-LAST:event_btnListPacientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPsicologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPsicologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPsicologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuPsicologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuPsicologo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisponAtendimento;
    private javax.swing.JButton btnListPacientes;
    private javax.swing.JButton btnListProntuarios;
    private javax.swing.JButton btnListSolicita;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblUserPsicologo;
    // End of variables declaration//GEN-END:variables
}